server:
  useSSL: false
  httpPort: 8080
  httpsPort: 4430
  my-ssl:
    key-store: classpath:https/SHA256withRSA_wy20160213.site.jks
    key-store-password: 1234
    key-store-type: JKS

spring:
  profiles:
    active: pro
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      indent_output: true
      fail_on_empty_beans: true
    deserialization:
      fail_on_unknown_properties: true
    default-property-inclusion: always
    parser:
      allow_unquoted_control_chars: false
      allow_single_quotes: false
    generator:
      ignore_unknown: false
    mapper:
      use_annotations: true
  mvc:
    throw-exception-if-no-handler-found: true #没有MvcHandler时报错
  resources:
    add-mappings: false #关闭Mvc静态资源自动映射
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: redis #缓存类型
    redis:
      time-to-live: -1 #-1永不过期,1d为1天
      use-key-prefix: true #是否开启缓存前缀
      key-prefix: 'simple_pms::' #缓存前缀
      cache-null-values: true #是否缓存null值
  security:
    default-password: e10adc3949ba59abbe56e057f20f883e

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: indi.simple.pms.entity.dataobject
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      insert-strategy: not_null
      update-strategy: not_null
      select-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: false
    auto-mapping-unknown-column-behavior: warning
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-generated-keys: true
    default-executor-type: reuse
    jdbc-type-for-null: NULL

logging:
  config: classpath:logback-${spring.profiles.active}.xml
  level:
    org.springframework.web: info
    org.springframework.data.elasticsearch.client.WIRE: trace #设置ES客户端日志级别为trace才能看到具体查询过程
    com.zaxxer.hikari: debug

jwt:
  system:
    header: Authorization
    expiration: 1440 #单位为分钟
  wechat:
    header: Authorization
    expiration: 1440 #单位为分钟

captcha:
  size: 4
  ttl: 2
  width: 112
  height: 48
